name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: testcli
      run: echo "${{ vars.KEYSTORE_STORE_FILE_PATH }}"
    - name: testcli2
      env:
        KEYSTORE_STORE_FILE_PATH: ${{ vars.KEYSTORE_STORE_FILE_PATH }}
      run: echo $KEYSTORE_STORE_FILE_PATH
    - name: Generate keystore.properties
      run: |
        cat <<EOF > keystore.properties
        storeFile:${{ vars.KEYSTORE_STORE_FILE_PATH }}
        storePassword:${{ secrets.KEYSTORE_STORE_PASSWORD }}
        keyAlias:${{ secrets.KEYSTORE_KEY_ALIAS }}
        keyPassword:${{ secrets.KEYSTORE_KEY_PASSWORD }}
        EOF
    - name: Generate keystore.jks
      run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > keystore.jks
    - name: Build with Gradle
      run: ./gradlew bundleRelease
    - name: Upload AAB
      uses: actions/upload-artifact@v4.3.3
      with:
        name: subspace
        path: app/build/outputs/bundle/release/app-release.aab
      
